config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :customers, controllers: { registrations: 'registrations' }

  root to: 'pages#index'
  get '/customers' => 'customers#index'

  resources :editables
  get '/customers/dashboard' => 'customers#show'
  resources :customers, except: [:show]
  get '/employees/dashboard' => 'employees#show'

  get '/wholesalers' => 'wholesalers#index'
  get '/wholesalers/new' => 'wholesalers#new'
  post '/wholesalers' => 'wholesalers#create'
  get 'wholesalers/:id' => 'wholesalers#show', as: 'wholesalers_show'
  get 'wholesalers/:id/edit' => 'wholesalers#edit'
  patch 'wholesalers/:id' => 'wholesalers#update'

  get '/about' => 'pages#about'
  get '/coffee_club' => 'pages#coffee_club'
  get '/contact' => 'pages#contact'
  get '/faqs' => 'pages#faqs'

  get '/menu' => 'pages#menu'
  get '/menus/new' => 'menus#new'
  post '/menus' => 'menus#create'
  get '/menus/:id/edit' => 'menus#edit'
  patch '/menus/:id' => 'menus#update'
  delete '/menus/:id' => 'menus#destroy'

  get '/categories/new' => 'categories#new'
  post '/categories' => 'categories#create'
  get '/categories/:id/edit' => 'categories#edit'
  patch '/categories/:id' => 'categories#update'
  delete '/categories/:id' => 'categories#destroy'

  get '/cart', to: 'carted_products#index'
  patch '/cart', to: 'carted_products#update_address', as: 'cart_update_address'

  resources :carted_subscriptions, only: [:index, :create, :edit, :update, :destroy]
  resources :carted_products, only: [:index, :create, :update]

  get '/orders/new/' => 'orders#new'
  get '/orders/new:order_id' => 'orders#create'
  patch '/orders/:order_id/:shipping_id' => 'orders#update'
  get '/orders/show/:id' => 'orders#show'
  get '/orders/create' => 'orders#create', as: 'orders_create'

  # get '/subscriptions/new' => 'subscriptions#new'

  resources :products
  get '/subscriptions' => 'products#subscriptions'
  resources :charges

  namespace :api do
    get '/customers' => 'customers#index'
    patch '/customers/:id' => 'customers#update'

    get '/employees' => 'employees#index'



    get '/products' => 'products#index'

    get '/subscriptions' => 'subscriptions#index'
    post '/subscriptions' => 'subscriptions#create'

    patch '/carted_products/:id/' => 'carted_products#update'
    delete '/carted_products/:id' => 'carted_products#destroy'

    patch '/carted_subscriptions' => 'carted_subscriptions#update'
  end
end

app/models/carted_product.rb
class CartedProduct < ApplicationRecord
  belongs_to :customer, optional: true
  validates :quantity, :product_id, :customer_id, :price, :status, presence: { message: 'Please enter all fields' }
  validates :sku, presence: { message: 'Please select a bean style' }
  validates :name, presence: { message: 'Please select a plan' }
  validates :quantity, numericality: { greater_than: 0, message: 'Please select a quantity' }
  belongs_to :order, optional: true

  def self.my_carted(customer_id)
    carted_products = where(status: 'carted', customer_id: customer_id)
    carted_products
  end
end

app/controllers/admin/carted_products_controller.rb
module Admin
  class CartedProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = CartedProduct.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   CartedProduct.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/carted_products_controller.rb
class Api::CartedProductsController < ApplicationController
  before_action :load_carted_product
  def update
    @carted_product.update(carted_product_params)
    if @carted_product.save
      render json: @carted_product
    else
      render json: { error: @carted_product.errors.full_messages }
    end
  end

  def destroy
    @carted_product.destroy
    render json: @carted_product
  end

  private

  def load_carted_product
    @carted_product = CartedProduct.find(params[:id])
  end

  def carted_product_params
    params.permit(:quantity)
  end

end

app/controllers/carted_products_controller.rb
class CartedProductsController < ApplicationController
  before_action :authenticate_customer!, only: [:index]
  def create
    carted_product = CartedProduct.find_by(
      status: 'carted',
      customer_id: guest_or_customer_id,
      sku: params[:sku]
    )
    if carted_product
      carted_product.quantity = carted_product.quantity.to_i + params[:quantity].to_i
      if carted_product.save
        flash[:success] = "Product quantity increased by #{params[:quantity]}"
        redirect_to '/cart'
      end
    else
      @product = StripeCache.new.product(params[:product_id])
      price = @product.skus.data.find { |sku| sku.id == params[:sku] } .price
      carted_product = CartedProduct.new(
        quantity: params[:quantity],
        product_id: params[:product_id],
        sku: params[:sku],
        customer_id: guest_or_customer_id,
        status: 'carted',
        price: price,
        name: @product.name
      ) ### supposed to catch and up the quantity if its the same ###
      if carted_product.save
        flash[:success] = 'Product Added to Cart!'
        redirect_to '/products'
      else
        flash[:error] = carted_product.errors.values.join(', ').gsub(/[']/, "\\\\\'")
        redirect_to "/products/#{params[:product_id]}"
      end
    end
  end

  def index
    @customer = current_customer || Customer.new
    @carted_products = @customer.carted_products.where(status: 'carted')
    @carted_subscriptions = @customer.current_subscription.status == 'pending' ? @customer.current_subscription.products['items'] : []
    @products_total = @carted_products.sum { |s| s.price * s.quantity }
    gon.push(
      cartedProducts: @carted_products,
      cartedSubscriptions: @carted_subscriptions
    )
    stripe_products = Stripe::Product.list(limit: 100).data
    @carted_subscriptions.map! do |item|
      sku = item['parent']
      product_id = Stripe::SKU.retrieve(sku).product
      product_name = stripe_products.find { |p| p.id == product_id } .name
      item.merge({ 'description' => product_name })
    end
    if @carted_products.empty? && @carted_subscriptions.empty?
      flash[:warning] = 'Your cart is currently empty.'
      redirect_to '/'
    end
    @address_validation = current_customer.address_validation_response
  end

  def update_address
    current_customer.update(address_params)
    redirect_to cart_path
  end

  private

  def address_params
    params.require(:customer).permit(:first_name, :last_name, :address, :address2, :city, :state, :zip_code)
  end
end

app/helpers/api/carted_products_helper.rb
module Api::CartedProductsHelper
end

app/helpers/carted_products_helper.rb
module CartedProductsHelper
end

app/views/carted_products/index.html.erb
<body id="botysbackground" class="carted_products index">
  <div class="container">
    <h3 class="center lobster-font gray"> Shopping Cart </h3>
    <div class="row">
      <div class="col s12 m6 l6">
        <div class="Checkout">
          <h5 class="LobsterCenter">Shipping Information</h5>
          <%= form_for(@customer, url: cart_update_address_path) do |f|%>
            <%= f.label :first_name %>
            <%= f.text_field :first_name %>
            <%= f.label :last_name %>
            <%= f.text_field :last_name %>
            <%= f.label :address  %>
            <%= f.text_field :address %>
            <%= f.label :address2  %>
            <%= f.text_field :address2 %>
            <%= f.label :city %>
            <%= f.text_field :city %>
            <%= f.label :state %>
            <div>
              <%= f.select :state, options_for_select(us_states, @customer.state) %>
            </div>
            <%= f.label :zip_code  %>
            <%= f.text_field :zip_code %>
            <input type="submit" value="Update Address" class="waves-effect btn addsAjax" />
          <% end %>
        </div>
      </div>
      <div class="col s12 m6 l6">
        <div class="Checkout">
          <p>
            <%= @address_validation.validation_results.is_valid ? 'Valid Billing Address:' : 'Invalid Billing Address:' %>
          </p>
          <p><%= @address_validation.street1 %></p>
          <p>
            <%= @address_validation.city%>
            <%= @address_validation.state %>
            <%= @address_validation[:zip] %>
          </p>
        </div>
        <div class="Checkout">
          <div class="OrderSummary">
            <h5 class="LobsterCenter">Order Summary</h5>
            <% unless @carted_products.empty? %>
              <h5 class="LobsterCenter ultraGrey">Products</h5>
              <ul>
                <% @carted_products.each do |product| %>
                  <li id="id<%=product.id%>" >
                    <div class="col s12 productView">
                      <div class="col s6 m6">
                        <%= product.name %>
                      </div>
                      <div class="col s4 m4 quantity">
                        <input class="productEdit" type="number" step="1" value="<%=product.quantity%>">
                        <div class="quantity-nav red-circle">
                          <div class="quantity-button quantity-up">+</div>
                          <div class="quantity-button quantity-down">-</div>
                        </div>
                      </div>
                      <div class="col s1 m2">
                        <a class="btn-floating btn-tiny waves-effect waves-light icon-bg-color deleteProduct"><i class="material-icons">delete</i></a>
                      </div>
                    </div>
                  </li>
                <%end%>
              </ul>
            <% end %>
            <% unless @carted_subscriptions.empty? %>
              <h5 class="LobsterCenter ultraGrey">Subscriptions</h5>
              <ul>
                <% @carted_subscriptions.each do |product| %>
                  <li id="id<%= product['parent'] %>" >
                    <div class="col s12 subscriptionView">
                      <div class="col s6 m6">
                        <%= product['description'] %>
                      </div>
                      <div class="col s4 m4 quantity">
                        <input class="subscriptionEdit" type="number" step="1" value="<%=product['quantity']%>">
                        <div class="quantity-nav red-circle">
                          <div class="quantity-button quantity-up">+</div>
                          <div class="quantity-button quantity-down">-</div>
                        </div>
                      </div>
                      <div class="col s1 m2">
                        <a class="btn-floating btn-tiny waves-effect waves-light icon-bg-color deleteSubscription"><i class="material-icons">delete</i></a>
                      </div>
                    </div>
                  </li>
                <% end %>
              </ul>
            <% end %>
          </div>
          <% if @address_validation.validation_results.is_valid %>
            <%= button_to(
              'Check Out',
              orders_create_path,
              method: :get,
              form_class: "waves-effect btn"
            ) %>
          <% else %>
            <p class="red-text">You must have a valid billing address to check out</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>