config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :customers, controllers: { registrations: 'registrations' }

  root to: 'pages#index'
  get '/customers' => 'customers#index'

  resources :editables
  get '/customers/dashboard' => 'customers#show'
  resources :customers, except: [:show]
  get '/employees/dashboard' => 'employees#show'

  get '/wholesalers' => 'wholesalers#index'
  get '/wholesalers/new' => 'wholesalers#new'
  post '/wholesalers' => 'wholesalers#create'
  get 'wholesalers/:id' => 'wholesalers#show', as: 'wholesalers_show'
  get 'wholesalers/:id/edit' => 'wholesalers#edit'
  patch 'wholesalers/:id' => 'wholesalers#update'

  get '/about' => 'pages#about'
  get '/coffee_club' => 'pages#coffee_club'
  get '/contact' => 'pages#contact'
  get '/faqs' => 'pages#faqs'

  get '/menu' => 'pages#menu'
  get '/menus/new' => 'menus#new'
  post '/menus' => 'menus#create'
  get '/menus/:id/edit' => 'menus#edit'
  patch '/menus/:id' => 'menus#update'
  delete '/menus/:id' => 'menus#destroy'

  get '/categories/new' => 'categories#new'
  post '/categories' => 'categories#create'
  get '/categories/:id/edit' => 'categories#edit'
  patch '/categories/:id' => 'categories#update'
  delete '/categories/:id' => 'categories#destroy'

  get '/cart', to: 'carted_products#index'
  patch '/cart', to: 'carted_products#update_address', as: 'cart_update_address'

  resources :carted_subscriptions, only: [:index, :create, :edit, :update, :destroy]
  resources :carted_products, only: [:index, :create, :update]

  get '/orders/new/' => 'orders#new'
  get '/orders/new:order_id' => 'orders#create'
  patch '/orders/:order_id/:shipping_id' => 'orders#update'
  get '/orders/show/:id' => 'orders#show'
  get '/orders/create' => 'orders#create', as: 'orders_create'

  # get '/subscriptions/new' => 'subscriptions#new'

  resources :products
  get '/subscriptions' => 'products#subscriptions'
  resources :charges

  namespace :api do
    get '/customers' => 'customers#index'
    patch '/customers/:id' => 'customers#update'

    get '/employees' => 'employees#index'



    get '/products' => 'products#index'

    get '/subscriptions' => 'subscriptions#index'
    post '/subscriptions' => 'subscriptions#create'

    patch '/carted_products/:id/' => 'carted_products#update'
    delete '/carted_products/:id' => 'carted_products#destroy'

    patch '/carted_subscriptions' => 'carted_subscriptions#update'
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Product.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Product.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/products_controller.rb
class Api::ProductsController < ApplicationController
  def index
    @products = Stripe::Product.list
    render "index.json.jbuilder"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  def index
    @products = StripeCache.new.products
  end

  def show
    @product = Stripe::Product.retrieve(id: params[:id])
    if @product.metadata['plans'] && current_customer&.current_subscription&.status != 'active'
      @plans = @product.metadata.plans.split(',')
      plan_names = { w: 'Weekly', b: 'Bi-Weekly', m: 'Monthly' }
      @plans.map! { |p| [plan_names[p.to_sym], p] }
      @plans.unshift(['One Time Purchase', ''])
    end
    @skus = @product.skus.data
    @skus.select! do |sku|
      sku.inventory&.quantity&.positive? || (sku.inventory.type == 'infinite')
    end
    @skus.map! do |sku|
      # product_name = @product.name
      attributes = sku.attributes.map { |pr| pr[1] } .join(', ')
      cost = number_to_currency(sku.price.to_f / 100)
      ["#{attributes} #{cost}", sku.id]
    end
    render partial: 'form_for_buying_products', layout: false if request.xhr?
  end

  def subscriptions
    @subscriptions = Stripe::Plan.list(limit: 50)
  end
end

app/helpers/api/products_helper.rb
module Api::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form_for_buying_products.html.erb
<%= form_tag "/carted_products", method: :post do%>
  <% if @plans %>
    <div class="section" style="height:100px;">
      <div class="row">
        <div class="input-field plan_select" id="plan_id">
          <%= select_tag :plan ,options_for_select(@plans)%>
          <label>Plan</label>
        </div>
      </div>
    </div>
  <% end %>

  <% if @product.attributes.length == 0 %>
    <%= hidden_field_tag :sku, @skus.first[1] %>
  <% else %>
    <div class="section" style="height:100px;">
      <div class="row">
        <div class="input-field plan_select" id="plan_id">
          <%= select_tag :sku ,options_for_select(@skus)%>
          <label><%= @product.attributes.first.titleize %></label>
        </div>
      </div>
    </div>
  <% end %>

  <div class="section" style="height:100px;">
    <div class="row">
      <div class="input-field">
        <%= select_tag :quantity, options_for_select((1..10).to_a) %>
        <label>Quantity</label>
      </div>
    </div>
  </div>
  <%= hidden_field_tag :product_id, @product.id %>
  <%= hidden_field_tag :name, @product.name %>
  <% if @skus.length != 0 %>
    <% if customer_signed_in? %>
      <button class="btn waves-effect waves-light" type="submit" name="submit">
        Add to Cart
      </button>
    <% elsif current_employee %>
      <div class = "col s6">
        <a href="#modal2" class="btn waves-effect waves-light modal-trigger" data-delay="5">Add to Cart</a>
      </div>
    <% else %>
      <div class="col s6">
        <a href="#modal1" class="btn waves-effect waves-light modal-trigger" data-delay="5" data-tooltip="Add to cart">Add to Cart</a>
      </div>
    <% end %>
  <% else %>
    <div class="col s6">Product is currently sold out</div>
  <% end %>
  <br>
  <br>
<% end %>

app/views/products/_modal_for_employee.html.erb
<div id="modal2" class="modal modal-fixed-footer" style="color: white">
    <div class="modal-content">
        <h4>Please sign out as an employee to buy things</h4>
    </div>
     <div class="modal-footer">
      <a href="#!" class="modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
</div>

app/views/products/index.html.erb
<div class="container padding-top">
  <h1>
    <span class="lobster-font">Products</span>
  </h1>
  <div class="row">
    <%@products.each do |product|%>
      <div class="col l6 s12 m12">
        <div class="card medium">
          <div class="card-image">
            <img class="activator" img src="<%=product.images[0]%>">
          </div>

          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%=product.name%></span>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%=product.name%>
              <i class="material-icons right">close</i>
            </span>
            <div class="description">
              <div class="innercard">
                <% if product.description %>
                  <p> <%= product.description.truncate(150) %></p>
                <% end %>
                <p>Starting at <%= starting_price(product) %></p>
                <div class="section">
                  <div class="row">
                    <div class="col s6">
                      <a href="/products/<%= product.id %>" class="btn-large btn-floating waves-effect waves-light botyred tooltipped" type="submit" name="action" data-delay="5" data-tooltip="More info"><i class="material-icons large">info_outline</i></a>
                    </div>
                    <% if customer_signed_in? %>
                      <div class="col s6">
                        <a href="#" id="id<%=product.id%>" class="add btn-large
                          btn-floating waves-effect waves-light botyred tooltipped" data-delay="5" data-tooltip="Add to cart"><i class="material-icons md-24">add_shopping_cart</i></a>
                      </div>
                    <% elsif employee_signed_in? %>
                      <div class="col s6">
                        <a href="#modal2" class="btn-large
                          btn-floating waves-effect waves-light tooltipped modal-trigger" data-delay="5" data-tooltip="Add to cart"><i class="material-icons md-24">add_shopping_cart</i></a>
                      </div>
                    <% else %>
                      <div class="col s6">
                        <a href="#modal1" class="btn-large
                          btn-floating waves-effect waves-light tooltipped modal-trigger" data-delay="5" data-tooltip="Add to cart"><i class="material-icons md-24">add_shopping_cart</i></a>
                      </div>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
            <div class="product_form"></div>
          </div>
        </div>
      </div>
    <%end%>
  </div>
  <%= render "customers/shared/modal_for_sign_in.html.erb" %>
  <%= render "modal_for_employee" %>
</div>

app/views/products/show.html.erb
<%#= react_component('ProductMessage', name: @product.name ) %>

<div id="index-banner" class="parallax-container">
  <div class="section no-pad-bot">
    <div class="container">
      <br><br>
      <h1 class="header center text-lighten-2 title">
        <span class="lobster-font-center"><%= @product.name %></span>
      </h1>
    </div>
  </div>
  <div class="parallax"><img class="activator" src="<%= @product.images[1]%>"></div>
</div>

<div class="container">
  <div class="section">
    <div class="row">
      <span class="garamond-font"><%= @product.description %></span>
    </div>
  </div>
</div>

<div style="width: 100%;">
  <div style="float:left; width: 50%">
    <div id="one-time-buy" class="col s12">
      <div class="container">
        <div class="row">
          <h3 class="lobster-font gray">Options for purchase</h3>
        </div>
        <%= render "form_for_buying_products" %>

      </div>
    </div>
  </div>

</div>
<%= render "customers/shared/modal_for_sign_in.html.erb" %>
<%= render "modal_for_employee" %>


<div style="clear:both"></div>

app/views/products/subscriptions.html.erb
  <div class="container">
    <div class="section">
      <div class="row">
        <div class="col s12 left">
          <h3><i class="mdi-content-send brown-text"></i></h3>
          <h5>Fresh beans in your mailbox!</h5>
          <h6>Fresh Back of the Yards, every month, delivered right to your doorstep. You don't have to do a thing!</h6> 
          <h6>Never run out of coffee again. Starting at $12 per shipment.</h6>
        </div>
      </div>
    
      <div class = "row" >
        <%@subscriptions.each do |subscription|%>
        <div class ="col s12 m4">
          <div class="card medium">
            <div class= "card-image">
              <img class="activator">
              <p class="center"> <%=image_tag("botycover.jpg", alt: "Unsplashed background img 3")%></p>
            </div>
            <div class="card-content">
              <span class="card-title activator grey-text text-darken-4"><%=subscription.name%></span>
              </span>
            </div>
            <div class="card-reveal">
              <span class="card-title grey-text text-darken-4"><%=subscription.name%>
                <i class="material-icons right">close</i></span>
              <p><%=number_to_currency(subscription.amount.to_f / 100)%> a month.</p>
              <a href="/subscriptions" button class="btn waves-effect waves-red " type="submit" name="action">Go to product</a>
            </div>
          </div>
        </div>
        <%end%>
      </div>
    </div>
  </div>