config/routes.rb
Rails.application.routes.draw do
  devise_for :employees
  devise_for :customers, controllers: { registrations: 'registrations' }

  root to: 'pages#index'
  get '/customers' => 'customers#index'

  resources :editables
  get '/customers/dashboard' => 'customers#show'
  resources :customers, except: [:show]
  get '/employees/dashboard' => 'employees#show'

  get '/wholesalers' => 'wholesalers#index'
  get '/wholesalers/new' => 'wholesalers#new'
  post '/wholesalers' => 'wholesalers#create'
  get 'wholesalers/:id' => 'wholesalers#show', as: 'wholesalers_show'
  get 'wholesalers/:id/edit' => 'wholesalers#edit'
  patch 'wholesalers/:id' => 'wholesalers#update'

  get '/about' => 'pages#about'
  get '/coffee_club' => 'pages#coffee_club'
  get '/contact' => 'pages#contact'
  get '/faqs' => 'pages#faqs'

  get '/menu' => 'pages#menu'
  get '/menus/new' => 'menus#new'
  post '/menus' => 'menus#create'
  get '/menus/:id/edit' => 'menus#edit'
  patch '/menus/:id' => 'menus#update'
  delete '/menus/:id' => 'menus#destroy'

  get '/categories/new' => 'categories#new'
  post '/categories' => 'categories#create'
  get '/categories/:id/edit' => 'categories#edit'
  patch '/categories/:id' => 'categories#update'
  delete '/categories/:id' => 'categories#destroy'

  get '/cart', to: 'carted_products#index'
  patch '/cart', to: 'carted_products#update_address', as: 'cart_update_address'

  resources :carted_subscriptions, only: [:index, :create, :edit, :update, :destroy]
  resources :carted_products, only: [:index, :create, :update]

  get '/orders/new/' => 'orders#new'
  get '/orders/new:order_id' => 'orders#create'
  patch '/orders/:order_id/:shipping_id' => 'orders#update'
  get '/orders/show/:id' => 'orders#show'
  get '/orders/create' => 'orders#create', as: 'orders_create'

  # get '/subscriptions/new' => 'subscriptions#new'

  resources :products
  get '/subscriptions' => 'products#subscriptions'
  resources :charges

  namespace :api do
    get '/customers' => 'customers#index'
    patch '/customers/:id' => 'customers#update'

    get '/employees' => 'employees#index'



    get '/products' => 'products#index'

    get '/subscriptions' => 'subscriptions#index'
    post '/subscriptions' => 'subscriptions#create'

    patch '/carted_products/:id/' => 'carted_products#update'
    delete '/carted_products/:id' => 'carted_products#destroy'

    patch '/carted_subscriptions' => 'carted_subscriptions#update'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders
  has_many :carted_products
  has_many :carted_subscriptions
  has_one :wholesaler

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :zip_code, presence: true, on: :update

  before_create :assign_customer_id, on: :create

  def assign_customer_id
    customer = Stripe::Customer.create(email: email)
    self.stripe_customer_id = customer.id
  end

  def subscriptions_total(id)
    @customer = Stripe::Customer.retrieve(id)
    @subscriptions_total = 0
    @customer.subscriptions.data.each do |subscription|
      @subscriptions_total += (subscription.items.data[0].quantity * (subscription.items.data[0].plan.amount * 0.01))
    end
    @subscriptions_total
  end

  def self.guest_customer?(id)
    Customer.find_by(id: id)
  end

  def self.create_guest_cutomer(id)
    customer = Customer.new(id: id, email: id)
    customer.save(validate: false)
    customer
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def customer_address
    {
      line1: address,
      line2: address2,
      city: city,
      state: state,
      country: 'US',
      postal_code: zip_code
    }
  end

  def default_address
    {
      line1: '2059 W 47th St',
      city: 'Chicago',
      country: 'US',
      postal_code: '60609'
    }
  end

  def address_validation_response
    begin
      address_to = Shippo::Address.create(
        name: full_name,
        street1: address,
        street2: address2,
        city: city,
        state: state,
        zip: zip_code,
        country: 'US',
        validate: true
      )
    rescue
      p ' ******** SHIPPO API ERROR ********* '
      return 'Sorry, Try Again'
    end
    address_to
  end

  def valid_shipping_address?
    begin
      address_to = Shippo::Address.create(
        name: full_name,
        street1: address,
        street2: address2,
        city: city,
        state: state,
        zip: zip_code,
        country: 'US',
        validate: true
      )
    rescue
      p ' ******** SHIPPO API ERROR ********* '
      return false
    end
    p address_to
    address_to.validation_results.is_valid
  end

  def carted_items
    # products = carted_products.where(status: 'carted')
    #   .map do |o|
    #     {
    #       type: 'sku',
    #       parent: o.sku,
    #       quantity: o.quantity
    #     }
    #   end
    quantities = Hash.new(0)
    carted_products.where(status: 'carted').each do |product|
      quantities[product.sku] += product.quantity
    end
    if current_subscription.status == 'pending'
      current_subscription.products['items'].each do |product|
        quantities[product['parent']] += product['quantity']
      end
    end
    quantities.map do |sku, quantity|
      {
        type: 'sku',
        parent: sku,
        quantity: quantity
      }
    end
  end

  def carted_products_and_subscription_quantity
    product_quantity = carted_products.where(status: 'carted').map(&:quantity)&.sum || 0
    subscription_quantity = current_subscription.status == 'pending' ? current_subscription.quantity : 0
    product_quantity + subscription_quantity
  end

  def current_subscription
    @subscriptions = carted_subscriptions.order(:created_at)
    no_subs = @subscriptions.empty? || @subscriptions.last.status == 'inactive'
    return carted_subscriptions.create if no_subs
    @subscriptions.last
  end
end

app/controllers/admin/customers_controller.rb
module Admin
  class CustomersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Customer.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Customer.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/api/customers_controller.rb
class Api::CustomersController < ApplicationController
  def index
    @customers = Customer.all
    render 'index.json.jbuilder'
  end

  def update
    @customer = Customer.find_by(id: params[:id])
    unless @customer.update(customer_params)
      render json: { errors: @customer.errors.full_messages }, status: 422
      return
    end
    StripeTool.customer_shipping_update(@customer)
    if params[:subscription]
      valid_shipping_address = @customer.valid_shipping_address?
      render json: {
        customer: @customer,
        valid_shipping_address: valid_shipping_address
      }
    else
      @order = StripeTool.create_order(@customer)
      render json: @order
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:first_name,
                                     :last_name,
                                     :address,
                                     :address2,
                                     :city,
                                     :state,
                                     :zip_code)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!, except: [:index]
  before_action :authenticate_employee!, only: [:index]
  before_action :load_current_customer, only: [:show, :edit, :update]

  def index
    @customers = Customer.all
  end

  def show
    subscription = @customer.current_subscription
    @subscription_items = subscription.products['items']
    stripe_products = Stripe::Product.list(limit: 100).data
    @subscription_items.map! do |item|
      sku = item['parent']
      product_id = Stripe::SKU.retrieve(sku).product
      product_name = stripe_products.find { |p| p.id == product_id } .name
      item.merge('description' => product_name)
    end
    @next_date = subscription.next_order_date&.to_s(:long_ordinal)
  end

  def edit; end

  def update
    if @customer.update(customer_params)
      flash[:success] = 'Shipping address updated'
      StripeTool.customer_shipping_update(@customer)
      redirect_to '/customers/dashboard'
    else
      flash[:warning] = 'Unable to update address'
      render :edit
    end
  end

  private

  def load_current_customer
    @customer = current_customer
  end

  def customer_params
    params.require(:customer).permit(
      :first_name,
      :last_name,
      :address,
      :address2,
      :city,
      :state,
      :zip_code
    )
  end
end

app/helpers/api/customers_helper.rb
module Api::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/shared/_modal_for_sign_in.html.erb
<div id="modal1" class="modal modal-fixed-footer">
  <div class="modal-content">
    <ul id="tabs" class="tabs big">
      <li class="tab col s6"><a class="active" href="#tab1">Sign in</a></li>
      <li class="tab col s6"><a href="#tab2">Sign up</a></li>
    </ul>
    <br/>
    <div id="tab1">
      <h4>Please sign in to continue</h4>
      <%= form_for(:customer, :url => session_path(:customer)) do |f| %>
        <%= f.text_field :email, placeholder: 'Email' %>
        <%= f.password_field :password, placeholder: 'Password' %>
        <%= f.check_box :remember_me %>
        <%= f.label :remember_me %>
        <%= f.hidden_field :redirect, value: "cart" %>
        <br/>
        <%= f.submit 'Sign in', :class => "btn" %>
        <br/>
        <%= link_to "Forgot your password?", new_password_path(:customer)%>
      <% end %>
    </div>
    <div id="tab2" >
      <h4> Sign Up</h4>
        <%= form_for(:customer, :url => registration_path(:customer)) do |f| %>

        <div class="field">
          <%= f.label :first_name %><br />
          <%= f.text_field :first_name,autofocus: true, placeholder: 'First name' %>
        </div>

        <div class="field">
          <%= f.label :last_name %><br />
          <%= f.text_field :last_name,autofocus: true, placeholder: 'Last name' %>
        </div>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.text_field :email,autofocus: true, placeholder: 'Email' %>
        </div>

        <div class="field">
          <%= f.label :password %><br />
          <%= f.password_field :password, placeholder: 'Password' %>
        </div>

        <div class="field">
          <%= f.label :password_confirmation %><br />
          <%= f.password_field :password_confirmation, autocomplete: "off",placeholder: 'Password Confirmation' %>
        </div>

        <div class="field">
          <%= f.label :address %><br />
          <%= f.text_field :address, autofocus: true,placeholder: 'Address' %>
        </div>

        <div class="field">
          <%= f.label :Address_2 %><br />
          <%= f.text_field :address2, autofocus: true,placeholder: 'Address 2' %>
        </div>

        <div class="field">
          <%= f.label :city %><br />
          <%= f.text_field :city, autofocus: true,placeholder: 'City' %>
        </div>

        <div class="field">
          <%= f.label :state %><br />
          <%= f.select :state, options_for_select(us_states,selected:['Illinois', 'IL']) %>
        </div>

        <div class="field">
          <%= f.label :zip_code %><br />
          <%= f.text_field :zip_code, autofocus: true,placeholder: 'Zip Code' %>
        </div>

        <%= f.hidden_field :redirect, value: "cart" %>
        <%= f.submit 'Sign up', :class => "btn" %>
      <% end %>
    </div>
    <br/>
  </div>
</div>